### ISSUE TITLE
Sound queue can be interrupted by auto disconnect in unwanted cases

### ISSUE THREAD

**Issue by stuckinab0x** [UncleDave/DiscordSoundboardBot#37]
The bot clears the sound queue and disconnects when it is the only one left in the channel, even if there are remaining sounds queued from channels with connected users. This behavior could be changed e.g. to remove only sound items queued from empty channels.

**Comment by stuckinab0x** [comment]
https://github.com/UncleDave/DiscordSoundboardBot/blob/f938d4d6e1a81b6cff88acb19f49e5cbe7e210a5/src/bot/bot.ts#L63-L66

This will run in any case where someone leaves any channel that is now empty, including if they _join_ the bot's channel :))))))) Pretty sure it's cause `.every()` returns true on an empty array/collection.

**Comment by stuckinab0x** [comment]
https://github.com/UncleDave/DiscordSoundboardBot/blob/f938d4d6e1a81b6cff88acb19f49e5cbe7e210a5/src/bot/bot.ts#L63-L66

Okay so this DOES run any time somebody leaves ANY channel that is now empty.

I was thinking it would be causing it to do weird things currently, but it doesn't because we only try to leave the channel in question and not just disconnect regardless. But we need a different if to handle the sound player stuff.

**Comment by UncleDave** [comment]
Can we just pass the channel to `clear`?

```
this.context.soundQueue.clear(oldState.channel);
```

And have it do the thingg

**Comment by stuckinab0x** [comment]
Yeah we can expand `clear` a little if you want.

```ts
if (oldState.channel && oldState.channel.members.size && oldState.channel.members.every(x => x.id === this.client.user.id))
```
This will stop it from running on other channels (unfortunately `oldState.channel.members.size` will crash if it evaluates when `oldState.channel` is null) In case you didn't see my original comment, `every` returns true on empty arrays, aka every empty channel. 

Clearing one channel only is still a little sus tho.

**Comment by stuckinab0x** [comment]
It was because I was modifying the array while iterating so some of them were getting skipped. Nice meme, something like that had crossed my mind because when I queued a lot roughly half were getting skipped but I didn't think it would let you make that mistake.

Let's try this:
```
clear(voiceChannel: string = null) {
    if (voiceChannel) {
      const remain: SoundQueueItem[] = [];
      this.forEach(x => { if (x.channel.id !== voiceChannel) remain.push(x); });
      this.length = 0;
      super.push(...remain);
      return;
    }
    this.length = 0;
  }
```
So it's probably even more suitable that we have this in a method.

**Comment by UncleDave** [comment]
I think the time has come to switch from inheritance to composition with `SoundQueue`, cuz you're right that it's an issue that we're iterating over an array while also mutating it, I hadn't even thought of that.
